#! /bin/bash
#文件名: collectKeywords -p = [path]; -f = [fileTypes]/[from]; -r = [regularExpressionOfKeywords];  -t = [targetFileName]/[to];
#从文件中，分析出用到的Keywords。
#example:	collectKeywords -p ~/Workspace/KCCS_V13/CODE/webapp/page/desktopAdmin/ -f "*.js" -t "js.js"

LC_ALL=C
## startDefault Value
regularExp="[0-9]\{8\}"
## endDefault Value

## startRegion Option
while getopts "p:t:r:f:" optname
do
    case "$optname" in
        "p")
            path=$OPTARG
        ;;
        "t")
            fileTypes=$OPTARG
        ;;
		"r")
			regularExp=$OPTARG
		;;
        "f")
            targetFileName=$OPTARG
        ;;
        "?")
            echo "unknown option $OPTARG"
        ;;
        ":")
            echo "No argument value for option $OPTARG"
        ;;
        *)
        ## should not occur
            echo "unknown error while processing options"
        ;;
    esac
done
## endRegion Option

## collect key words in folder
for fType in "$fileTypes"
do

	echo "$fType"

	#this will get file name
	#find $path -name "$fType" -exec grep -isoh --exclude=*.swp --exclude=*.git* --exclude=*.svn* --color=auto "${regularExp}" {} \; -print >> ${targetFileName} #with found file names
	grep ${regularExp} -isorh --include=${fType} ${path} >> ${targetFileName}

done

## remove repeated keywords
declare -a keywordAry=()
echo ${#keywordAry[@]}
IFS=" ";
while read keyword
do
	tmpA=( ${keywordAry[@]/${keyword}/} )
	if [ ${#tmpA[@]} -eq ${#keywordAry[@]} ];
	then
		keywordAry=(${keywordAry[@]} ${keyword})
	else
		echo ${keyword}" +1."
	fi
done < ${targetFileName}
## write result to target file
echo ${keywordAry[@]}|tr " " "\n" > ${targetFileName}

vi ${targetFileName}
