#! /bin/bash -
#从.htm文件中提取javascript代码（只有一段内嵌代码时），并保存到.js/目录下同名.js文件中，然后重命名.htm为.html文件，并清除内嵌javascript代码，增加js文件引用。
jsFolderName="js"
htmFileType=".htm"
echo ${jsFolderName}
for fileName in `grep "<script type=\"text\/javascript\">" -rl --include=*${htmFileType} --exclude=*.git* --exclude=*.svn* --exclude=*.swp --exclude=*.js* --exclude=*.html* "."`
do
	mkdir -p ${jsFolderName}
	echo "Found ${htmFileType} file: $fileName"
	jsFileName="./${jsFolderName}/"${fileName%${htmFileType}}".js"
	#copy javascript code from htm file
	sed -n -e "/<script\ type=\"text\/javascript\">/,/<\/script>/w ${jsFileName}" ${fileName}
	sed -i -e '1d;$d;' ${jsFileName}
	echo ".js file:"${jsFileName}" is created."
	#rename htm file to html
	mv ${fileName} ${fileName}'l'
	echo "${fileName} is renamed to ${fileName}l"
	fileName=${fileName}'l'
	#rm javascript code from html file
	#regStr="\t<script type=\"text\/javascript\" src=\"${jsFileName}\">\n<\/head>"
	regStr='\t<script type="text/javascript" src="'${jsFileName}'"></script>\n</head>'
	regStr=${regStr//\//\\\/}
	regStr=${regStr//\ /\\\ }
	sed -i -e "/<script\ type=\"text\/javascript\">/,/<\/script>/g" -e "/^$/d" -e "s/<\/head>/${regStr}/g" ${fileName}
	echo "Removed js code from htm file."
	#sed -i -e "/<script\ type=\"text\/javascript\">/,/<\/script>/g" -e "/^$/d" ${fileName}
	#sed -i -e "s/<\/head>/${regStr}/g" ${fileName}
done
echo "Done."
