#! /bin/bash -
startbcpnet(){
	local gw=$(route -n | grep 0.0.0.0 | grep eth | awk '{print $(2)}')
	local result="startbcpnet result: ";
	sudo route add -net 192.168.0.0		 gw "${gw}" netmask 255.255.0.0 metric 25;
	sudo route add -net 172.16.10.0		 gw "${gw}" netmask 255.255.255.0 metric 25;
	sudo route add -net 221.237.182.205	 gw "${gw}" netmask 255.255.255.255 metric 25;
	sudo route add -net 54.230.23.0		 gw "${gw}" netmask 255.255.255.0 metric 25; # docs.sencha.com
		#local docs_sencha_com=$(nslookup docs.sencha.com |grep Address:[[:space:]][0-9.]*$);
		#echo ${docs_sencha_com//Address:/}
	echo $(addIPtoRouteByDomain "docs.sencha.com" "${gw}");
	echo $(addIPtoRouteByDomain "dict.youdao.com" "${gw}");
	echo $(addIPtoRouteByDomain "subclipse.tigris.org" "${gw}"); #eclipse subclipse plugin.;
#	for f in ${docs_sencha_com}
#	do
#		f=${f#Address:};
#		case "${f}" in
#			"")
#				continue ;;
#			*) echo "${f}"; sudo route add -net "${f}"	gw "${gw}" netmask 255.255.255.255 metric 25; ;;
#		esac
#	done
	result=${result}$(echo '' && route -n |grep "${gw}");
	#echo -n ${result};
	notify-send "${result}";
}
startbcpnet;
