#! /bin/bash -
#/home/wangz/bin/ssfws/minifyJS.sh -p /home/wangz/Workspace/eclipse/bcp/com.wisesoft.iimp.web/WebContent/static/js/extjs/application/ws/view/grid/ -e /home/wangz/Workspace/extjs-wise/application/ew/view/grid/ -s Panel.js.2014.07.01.in.short.js  -d Panel-min.js
minifyCMD(){
	local PRG="$0"
	local PRGDIR=`dirname "$PRG"`
	#notify-send "${PRGDIR}""/""NetOfficeCMD";
	local sourceBasePath=$1; #/media/sf_D_DRIVE/Workspace/2014-08-29_Net_Office/NEW/WebApplication1/WAAttendanceManagement/;
	local sourcePath="${sourceBasePath}$2";#Scripts/main/";
	local targetPath="${sourcePath}";
	local sourceList=$3;#"cmdlst";
	local mDate=$4;
	#cat ${sourcePath}${sourceList} | while read LINE; do if [ $(($(date +%s)-$(date --utc --reference=${sourcePath}${LINE} +%s))) -lt 60 ]; then /home/wangz/bin/ssfws/minifyJS.sh -e `dirname ${sourcePath}${LINE}` -s ${LINE} -n `dirname ${targetPath}${LINE}` -d ${LINE/%.js/-min.js} -x ".js"; fi; done;
	## .src.js
	#TMP=view/grid/; cp $TMP"Panel.js" $TMP"Panel.tmp.js" && uglifyjs -nc join_vars:false $TMP"Panel.tmp.js" | uglifyjs -b -o $TMP"Panel.tmp.js" && sed -i -e 's/utils("getProperty")("\([a-zA-Z0-9_$]\{1,\}\)")/\1/g' $TMP"Panel.tmp.js" && cat $TMP"Panel.tmp.js" | grep getPropert
	local FOPath="${sourcePath}";
	local FSPath="${sourcePath}FS/";
	local FMPath="${sourcePath}FM/";
	#FOS
	echo "BEGIN FOS";
	cat "${FOPath}${sourceList}" | while read LINE;
	do
		if [ "${LINE/add }" != "${LINE}" ] && [ "${LINE/.js}" != "${LINE}" ];
		then
			LINE="${LINE/add }";
			if [ $(($(date +%s)-$(date --utc --reference="${FOPath}${LINE}" +%s))) -lt 60 ];
			then
				#/home/wangz/bin/ssfws/minifyJS.sh -e `dirname ${sourcePath}${LINE}` -s ${LINE} -n `dirname ${targetPath}${LINE}` -d ${LINE/%.js/-min.js} -x ".js";
				#echo "updateFS:${FSPath}${LINE}";
				#mkdir -p "`dirname "${FSPath}${LINE}"`";
				#uglifyjs -nc -b beautify:true "${FOPath}"${LINE} -o "${FSPath}"${LINE};
				# for uglifyjs2
				#echo "uglifyjs \"${FOPath}${LINE}\" -c -b";
				#uglifyjs -o "${FSPath}${LINE}" -c -b quote-keys=true,indent-level=9,bracketize=true --comments "${FOPath}${LINE}";
				#uglifyjs -mt -ns --comments '^[\ \/]*\*\ \@' -b -o ${FSPath}${LINE} ${FOPath}${LINE};
				#uglifyjs -mt -ns -b -o ${FSPath}${LINE} ${FOPath}${LINE};
				#~/bin/ssfws/minifyJS.sh -e /media/sf_D_DRIVE/Workspace/2014-09-09_personalTools/jquery-collection/jquery-skinner/js/ -s jquery-skinner.js -d jquery-skinner-min.js
		#echo "~/bin/ssfws/minifyJS.sh -e '${FOPath}' -s '${LINE}' -d '${LINE/%.js/-min.js}'"
				$(~/bin/ssfws/minifyJS.sh -e "${FOPath}" -s "${LINE}" -d "${LINE/%.js/-min.js}" -m ${mDate});
			fi;
		fi;
	done;
	echo "END FOS"
}
minifyCMD "$@";
